name: Linting, testing, building
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    piplene:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [17.x]
        steps:
            - uses: actions/checkout@v2
            - name: Starting Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node_version: ${{ matrix.node-version }}

            - name: install modules
              run: make install

            - name: build production project
              run: make prod

            - name: typescript linting
              run: make lint

            - name: css linting
              run: make stylelint

            - name: unit testing
              run: make test

            - name: install modules
              run: npm install
